In [1]:
import numpy as np

### 대한민국 1990년부터의 연간 GDP를 바탕으로 불린 인덱싱

In [3]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [4]:
gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [6]:
mas = gdp_array > 10000 #새로운 이름을 붙여서 묶어주면 값만 뽑아낼 수 있음 불린 인덱싱 또는 마스킹이라고 함
gdp_array[mas] 

array([10385, 12565, 13403, 12398, 10672])

In [7]:
gdp_array[gdp_array > 10000] #이것도 OK!

array([10385, 12565, 13403, 12398, 10672])

In [11]:
(gdp_array > 10000) | (gdp_array < 8000)  # |는 or과 같은 뜻

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [12]:
gdp_array[(gdp_array > 10000) | (gdp_array < 8000) ]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [13]:
gdp_array[(gdp_array < 10000) & (gdp_array >= 8000)] # &는 and와 같음

array([8127, 8885, 8282])

In [14]:
gdp_array.mean() #평균값 구하기

9896.4

In [16]:
gdp_array.sum() #총 합

98964

In [17]:
gdp_array.min() #가장 작은 수

6610

In [18]:
gdp_array.max() #가장 큰 수

13403

In [19]:
gdp_array * 1200 #각 요소 값에 1200씩 다 곱해

array([ 7932000,  9164400,  9752400, 10662000, 12462000, 15078000,
       16083600, 14877600,  9938400, 12806400])

In [21]:
gdp_array = gdp_array * 1200
gdp_array

array([ 9518400000, 10997280000, 11702880000, 12794400000, 14954400000,
       18093600000, 19300320000, 17853120000, 11926080000, 15367680000])

In [24]:
gdp_us_array = np.array([36335, 37133, 38023, 39496, 41713, 44115, 38023, 39496, 41713, 44115])

In [25]:
gdp_us_array - gdp_array

array([ -9518363665, -10997242867, -11702841977, -12794360504,
       -14954358287, -18093555885, -19300281977, -17853080504,
       -11926038287, -15367635885])