In [1]:
import numpy as np

### 1990년부터 10년간의 GDP변화로 보는 인덱싱과 슬라이싱

In [2]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [3]:
gdp_array[0] #1990년의 gdp값을 인덱싱

np.int64(6610)

In [4]:
gdp_array[2]

np.int64(8127)

In [5]:
gdp_array[-1]

np.int64(10672)

In [6]:
gdp_array[[1, 3, 4]] #1, 3, 4번 자리에 있는 인덱스 값 모두 불러옴


array([ 7637,  8885, 10385])

In [7]:
array1 = np.array([2, 1, 3, 4])
gdp_array[array1]

array([ 8127,  7637,  8885, 10385])

In [8]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])